{
 "title": "Trading Dashboard",
 "description": "Trading Dashboard for Demo",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "PNL View",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "DEMO",
     "rawSql": "select * from realtime_data.positions_pnl_view"
    }
   ]
  },
  {
   "title": "Prices",
   "type": "barchart",
   "gridPos": { "h": 22, "w": 10, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "DEMO",
     "rawSql": "select * from realtime_data.prices ORDER BY symbol ASC;"
    }
   ]
  },
  {
   "title": "Latest Trade Snapshot",
   "type": "bargauge",
   "gridPos": { "h": 22, "w": 7, "x": 10, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "DEMO",
     "rawSql": "select * from realtime_data.trades"
    }
   ]
  },
  {
   "title": "Latest Position Aggregation",
   "type": "table",
   "gridPos": { "h": 22, "w": 7, "x": 17, "y": 13 },
   "targets": [
    {
     "dataset": "DEMO",
     "rawSql": "select * from realtime_data.positions_base_mv"
    }
   ]
  }
 ]
}